name: WordRank
main: com.lala.wordrank.WordRank
version: 1.1
author: 'LaLa'
commands:
    w:
        description: Word
        usage: |
               /<command> - See forum post for complete syntax