name: WordRank
main: com.lala.wordrank.WordRank
version: 1.2
author: LaLa, codename_B
commands:
    w:
        description: Word
        usage: |
               /<command> - See forum post for complete syntax
permissions:
    WordRank.*:
        description: Gives access to all WordRank commands
        children:
            WordRank.add: true
            WordRank.remove: true
            WordRank.remove.all: true
            WordRank.say: true
    WordRank.add:
        description: Allows you to add a word
        default: false
    WordRank.remove:
        description: Allows you to remove a word
        default: false
    WordRank.remove.all:
        description: Allows you to remove all words
        default: false
    WordRank.say:
        description: Allows you to be promoted by a word
        default: true