name: WordRank
main: com.lala.wordrank.WordRank
version: 1.2
author: LaLa, codename_B
commands:
    w:
        description: Word
        usage: |
               /<command> - See forum post for complete syntax